### ISSUE TITLE
Přesná odpověď je uznána pouze řádově

### ISSUE THREAD

**Issue by VojGin** [kokes/vaclavaky#25]
Viz obrázek:

![image](https://user-images.githubusercontent.com/5146396/73960053-851d1e00-490a-11ea-9e43-0779402ea743.png)

**Comment by kokes** [comment]
Jop, to je daný zaokrouhlenim, kdy 6.71 neni vlastně ta přesná odpověď. Dám tam porovnání zaokrouhlených hodnot.
