### ISSUE TITLE
Tour de France do vzdálenosti

### ISSUE THREAD

**Issue by kokes** [kokes/vaclavaky#30]
nějakou průměrnou, případně nedávnou (letošní)

případně přidat i převýšení

**Comment by kokes** [comment]
a čas, za kterej to ujedou

**Comment by JVancata** [comment]
3,484.2 km - 2020 - https://en.wikipedia.org/wiki/2020_Tour_de_France
3,365.8 km - 2019 - https://en.wikipedia.org/wiki/2019_Tour_de_France
3,351 km - 2018 - https://en.wikipedia.org/wiki/2018_Tour_de_France
3,540 km - 2017 - https://en.wikipedia.org/wiki/2017_Tour_de_France
3,529 km - 2016 - https://en.wikipedia.org/wiki/2016_Tour_de_France
3,360.3 km - 2015 - https://en.wikipedia.org/wiki/2015_Tour_de_France

(3484.2+3365.8+3351+3540+3529+3360.3)/6 = 3438.383333333333

**Comment by kokes** [comment]
https://github.com/kokes/vaclavaky/commit/db2f178f62bbb1271414a3d6996174fe5b92e064
